import React from 'react';
import {
  Clock,
  CheckCircle,
  UserCheck,
  Sparkles,
  ArrowRight,
} from 'lucide-react';
import { TaskItem, TaskStatus } from '../types';

interface ActionableItemsPageProps {
  tasks: TaskItem[];
  onUpdateStatus: (taskId: string, newStatus: TaskStatus) => void;
  onNavigateToDb: () => void;
}

export const ActionableItemsPage: React.FC<ActionableItemsPageProps> = ({
  tasks,
  onUpdateStatus,
  onNavigateToDb,
}) => {
  const awaitingApproval = tasks.filter((t) => t.status === 'Awaiting approval');
  const generatedTasks = tasks.filter((t) => t.status === 'Generated');
  const assignedTasks = tasks.filter((t) => t.status === 'Assigned');

  return (
    <div className="space-y-6 max-w-7xl mx-auto pb-12">
      {/* Header Info Banner */}
      <div className="p-5 rounded-[12px] bg-white border border-[#e2e8f0] shadow-[0px_1px_3px_rgba(0,0,0,0.04)] flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <div className="flex items-center gap-2.5">
            <h2 className="text-base font-bold text-[#0f172a] tracking-tight">
              Actionable Work Items
            </h2>
            <span className="text-[10px] font-semibold px-2.5 py-0.5 rounded-full bg-[#f1f5f9] text-[#475569] border border-[#e2e8f0]">
              {awaitingApproval.length + generatedTasks.length} Require Action
            </span>
          </div>
          <p className="text-xs text-[#64748b] mt-1 max-w-xl leading-relaxed">
            Tasks filed automatically by the AI audit and client discussions that need approval, assignment, or execution.
          </p>
        </div>

        <button
          onClick={onNavigateToDb}
          className="inline-flex items-center gap-1.5 px-3.5 py-2 rounded-[8px] bg-white hover:bg-[#f8fafc] text-[#0f172a] text-xs font-semibold border border-[#e2e8f0] transition-colors shadow-xs"
        >
          <span>Open Full Task DB</span>
          <ArrowRight className="w-3.5 h-3.5 text-[#94a3b8]" />
        </button>
      </div>

      {/* 1. AWAITING APPROVAL QUEUE (Trackly Monochrome Card) */}
      {awaitingApproval.length > 0 && (
        <div className="space-y-3">
          <h3 className="text-xs font-bold text-[#0f172a] uppercase tracking-wider flex items-center gap-2">
            <Clock className="w-3.5 h-3.5 text-[#64748b]" />
            Awaiting Client / Manager Approval ({awaitingApproval.length})
          </h3>
          <div className="grid gap-3">
            {awaitingApproval.map((task) => (
              <div
                key={task.id}
                className="p-5 rounded-[12px] bg-white border border-[#e2e8f0] flex flex-col md:flex-row md:items-center justify-between gap-4 shadow-[0px_1px_3px_rgba(0,0,0,0.02)]"
              >
                <div>
                  <div className="flex items-center gap-2 mb-1.5">
                    <span className="text-xs font-mono text-[#0f172a] font-bold">{task.id}</span>
                    <span className="text-[10px] font-semibold px-2 py-0.5 rounded-full bg-[#f1f5f9] text-[#0f172a] border border-[#e2e8f0]">
                      {task.lane} LANE
                    </span>
                    <span className="text-xs text-[#64748b] font-mono">{task.date}</span>
                  </div>
                  <div className="text-sm font-bold text-[#0f172a]">{task.task}</div>
                  <div className="text-xs text-[#64748b] mt-1">
                    Source: <span className="text-[#0f172a] font-medium">{task.source || 'Client Comms'}</span>
                  </div>
                </div>

                <div className="flex items-center gap-2 self-end md:self-center">
                  <button
                    onClick={() => onUpdateStatus(task.id, 'Assigned')}
                    className="px-3.5 py-2 rounded-[8px] bg-[#0f172a] hover:bg-[#1e293b] text-white font-semibold text-xs transition-colors flex items-center gap-1.5 shadow-xs"
                  >
                    <CheckCircle className="w-3.5 h-3.5" /> Approve & Assign
                  </button>
                  <button
                    onClick={() => onUpdateStatus(task.id, 'Completed')}
                    className="px-3.5 py-2 rounded-[8px] bg-white hover:bg-[#f8fafc] text-[#0f172a] text-xs font-semibold border border-[#e2e8f0] transition-colors shadow-xs"
                  >
                    Mark Done
                  </button>
                </div>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* 2. GENERATED BY AUDIT */}
      <div className="space-y-3">
        <h3 className="text-xs font-bold text-[#0f172a] uppercase tracking-wider flex items-center gap-2">
          <Sparkles className="w-3.5 h-3.5 text-[#64748b]" />
          Audit Generated Tasks Ready for Dispatch ({generatedTasks.length})
        </h3>
        <div className="grid gap-3">
          {generatedTasks.map((task) => (
            <div
              key={task.id}
              className="p-4 sm:p-5 rounded-[12px] bg-white border border-[#e2e8f0] hover:border-[#cbd5e1] flex flex-col md:flex-row md:items-center justify-between gap-3.5 transition-all shadow-[0px_1px_3px_rgba(0,0,0,0.03)]"
            >
              <div>
                <div className="flex flex-wrap items-center gap-2 mb-1.5">
                  <span className="text-xs font-mono text-[#64748b] font-bold">{task.id}</span>
                  <span className="text-[10px] font-semibold px-2 py-0.2 rounded-full bg-[#f1f5f9] text-[#0f172a] border border-[#e2e8f0]">
                    {task.lane}
                  </span>
                  {task.priority === 'High' && (
                    <span className="text-[10px] font-semibold text-[#0f172a] bg-[#f1f5f9] px-2 py-0.2 rounded-full border border-[#e2e8f0]">
                      High Priority
                    </span>
                  )}
                  <span className="text-xs text-[#94a3b8] font-mono">{task.date}</span>
                </div>
                <div className="text-sm font-bold text-[#0f172a]">{task.task}</div>
                <div className="text-xs text-[#64748b] mt-1">
                  Source: <span className="text-[#0f172a] font-medium">{task.source}</span>
                </div>
              </div>

              <div className="flex items-center gap-2 self-end md:self-center shrink-0">
                <button
                  onClick={() => onUpdateStatus(task.id, 'Assigned')}
                  className="px-3.5 py-2 rounded-[8px] bg-[#0f172a] hover:bg-[#1e293b] text-white font-semibold text-xs transition-colors flex items-center gap-1.5 shadow-xs"
                >
                  <UserCheck className="w-3.5 h-3.5" /> Assign Team
                </button>
                <button
                  onClick={() => onUpdateStatus(task.id, 'Completed')}
                  className="px-3.5 py-2 rounded-[8px] bg-white hover:bg-[#f8fafc] text-[#0f172a] text-xs font-semibold border border-[#e2e8f0] transition-colors shadow-xs"
                >
                  Done
                </button>
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* 3. CURRENTLY ASSIGNED & IN FLIGHT */}
      <div className="space-y-3">
        <h3 className="text-xs font-bold text-[#64748b] uppercase tracking-wider flex items-center gap-2">
          <UserCheck className="w-3.5 h-3.5 text-[#0f172a]" />
          Currently Assigned & In Progress ({assignedTasks.length})
        </h3>
        <div className="grid gap-3">
          {assignedTasks.map((task) => (
            <div
              key={task.id}
              className="p-4 sm:p-5 rounded-[12px] bg-white border border-[#e2e8f0] flex flex-col md:flex-row md:items-center justify-between gap-3 shadow-[0px_1px_3px_rgba(0,0,0,0.03)]"
            >
              <div>
                <div className="flex items-center gap-2 mb-1.5">
                  <span className="text-xs font-mono text-[#64748b] font-bold">{task.id}</span>
                  <span className="text-[10px] font-semibold px-2 py-0.2 rounded-full bg-[#f1f5f9] text-[#475569] border border-[#e2e8f0]">
                    {task.lane}
                  </span>
                  <span className="text-xs font-semibold text-[#0f172a]">
                    Assigned to: {task.assignedTo || 'Unspecified'}
                  </span>
                </div>
                <div className="text-sm font-semibold text-[#0f172a]">{task.task}</div>
              </div>

              <button
                onClick={() => onUpdateStatus(task.id, 'Completed')}
                className="px-3.5 py-2 rounded-[8px] bg-white hover:bg-[#f8fafc] text-[#0f172a] text-xs font-semibold border border-[#e2e8f0] transition-colors flex items-center gap-1.5 shadow-xs"
              >
                <CheckCircle className="w-3.5 h-3.5" /> Mark Completed
              </button>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
};
