import React from 'react';
import {
  Clock,
  CheckCircle,
  UserCheck,
  Sparkles,
  ArrowRight,
  AlertTriangle,
} from 'lucide-react';
import { TaskItem, TaskStatus } from '../types';

interface ActionableItemsPageProps {
  tasks: TaskItem[];
  onUpdateStatus: (taskId: string, newStatus: TaskStatus) => void;
  onNavigateToDb: () => void;
}

export const ActionableItemsPage: React.FC<ActionableItemsPageProps> = ({
  tasks,
  onUpdateStatus,
  onNavigateToDb,
}) => {
  const awaitingApproval = tasks.filter((t) => t.status === 'Awaiting approval');
  const generatedTasks = tasks.filter((t) => t.status === 'Generated');
  const assignedTasks = tasks.filter((t) => t.status === 'Assigned');

  return (
    <div className="space-y-5 max-w-7xl mx-auto pb-12">
      {/* Header Info Banner */}
      <div className="p-4 rounded-[8px] bg-white border border-[#efefef] shadow-[0px_1px_2px_rgba(0,0,0,0.02)] flex flex-col sm:flex-row sm:items-center justify-between gap-3">
        <div>
          <div className="flex items-center gap-2">
            <h2 className="text-sm font-bold text-[#010101] tracking-tight">
              Actionable Work Items
            </h2>
            <span className="text-[10px] px-2 py-0.5 rounded-[4px] bg-[#fefce8] text-[#a16207] border border-[#fef08a] font-medium">
              {awaitingApproval.length + generatedTasks.length} Require Immediate Action
            </span>
          </div>
          <p className="text-xs text-[#71717a] mt-0.5 max-w-xl">
            Tasks filed automatically by the AI audit and client discussions that need approval, assignment, or execution.
          </p>
        </div>

        <button
          onClick={onNavigateToDb}
          className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-[6px] bg-white hover:bg-[#fafafa] text-[#171717] text-xs font-medium border border-[#e3e3e3] transition-colors shadow-[0px_1px_2px_rgba(0,0,0,0.02)]"
        >
          <span>Open Full Task DB</span>
          <ArrowRight className="w-3.5 h-3.5" />
        </button>
      </div>

      {/* 1. AWAITING APPROVAL QUEUE */}
      {awaitingApproval.length > 0 && (
        <div className="space-y-2.5">
          <h3 className="text-xs font-bold text-[#a16207] uppercase tracking-wider flex items-center gap-1.5">
            <Clock className="w-3.5 h-3.5" />
            Awaiting Client / Manager Approval ({awaitingApproval.length})
          </h3>
          <div className="grid gap-2.5">
            {awaitingApproval.map((task) => (
              <div
                key={task.id}
                className="p-4 rounded-[8px] bg-[#fefce8]/60 border border-[#fef08a] flex flex-col md:flex-row md:items-center justify-between gap-3 shadow-[0px_1px_2px_rgba(0,0,0,0.02)]"
              >
                <div>
                  <div className="flex items-center gap-2 mb-1">
                    <span className="text-xs font-mono text-[#a16207] font-bold">{task.id}</span>
                    <span className="text-[10px] px-2 py-0.5 rounded-[4px] bg-white text-[#a16207] border border-[#fef08a] font-medium">
                      {task.lane} LANE
                    </span>
                    <span className="text-[10px] text-[#71717a] font-mono">{task.date}</span>
                  </div>
                  <div className="text-xs font-semibold text-[#18181b]">{task.task}</div>
                  <div className="text-[11px] text-[#71717a] mt-0.5">
                    Source: <span className="text-[#3f3f46] font-medium">{task.source || 'Client Comms'}</span>
                  </div>
                </div>

                <div className="flex items-center gap-2 self-end md:self-center">
                  <button
                    onClick={() => onUpdateStatus(task.id, 'Assigned')}
                    className="px-3 py-1.5 rounded-[6px] bg-[#16a34a] hover:bg-[#15803d] text-white font-medium text-xs transition-colors flex items-center gap-1.5 shadow-sm"
                  >
                    <CheckCircle className="w-3.5 h-3.5" /> Approve & Assign
                  </button>
                  <button
                    onClick={() => onUpdateStatus(task.id, 'Completed')}
                    className="px-3 py-1.5 rounded-[6px] bg-white hover:bg-[#fafafa] text-[#171717] text-xs font-medium border border-[#e3e3e3] transition-colors"
                  >
                    Mark Done
                  </button>
                </div>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* 2. GENERATED BY AUDIT (Pending Triage / Assignment) */}
      <div className="space-y-2.5">
        <h3 className="text-xs font-bold text-[#010101] uppercase tracking-wider flex items-center gap-1.5">
          <Sparkles className="w-3.5 h-3.5 text-[#2563eb]" />
          Audit Generated Tasks Ready for Dispatch ({generatedTasks.length})
        </h3>
        <div className="grid gap-2.5">
          {generatedTasks.map((task) => (
            <div
              key={task.id}
              className="p-3.5 rounded-[8px] bg-white border border-[#efefef] hover:border-[#d4d4d8] flex flex-col md:flex-row md:items-center justify-between gap-3 transition-colors shadow-[0px_1px_2px_rgba(0,0,0,0.02)]"
            >
              <div>
                <div className="flex items-center gap-2 mb-1">
                  <span className="text-xs font-mono text-[#71717a] font-bold">{task.id}</span>
                  <span
                    className={`text-[10px] px-1.5 py-0.2 rounded-[3px] font-medium ${
                      task.lane === 'TECHNICAL'
                        ? 'bg-[#eff6ff] text-[#2563eb] border border-[#bfdbfe]'
                        : 'bg-[#faf6fd] text-[#7c3aed] border border-[#ede9fe]'
                    }`}
                  >
                    {task.lane}
                  </span>
                  {task.priority === 'High' && (
                    <span className="text-[10px] font-semibold text-[#dc2626] flex items-center gap-0.5">
                      <AlertTriangle className="w-3 h-3" /> High Priority
                    </span>
                  )}
                  <span className="text-[10px] text-[#a1a1aa] font-mono">{task.date}</span>
                </div>
                <div className="text-xs font-semibold text-[#010101]">{task.task}</div>
                <div className="text-[11px] text-[#71717a] mt-0.5">
                  Source: <span className="text-[#3f3f46]">{task.source}</span>
                </div>
              </div>

              <div className="flex items-center gap-2 self-end md:self-center">
                <button
                  onClick={() => onUpdateStatus(task.id, 'Assigned')}
                  className="px-3 py-1.5 rounded-[6px] bg-[#171717] hover:bg-[#262626] text-white font-medium text-xs transition-colors flex items-center gap-1.5 shadow-sm"
                >
                  <UserCheck className="w-3.5 h-3.5" /> Assign Team
                </button>
                <button
                  onClick={() => onUpdateStatus(task.id, 'Completed')}
                  className="px-3 py-1.5 rounded-[6px] bg-white hover:bg-[#fafafa] text-[#171717] text-xs font-medium border border-[#e3e3e3] transition-colors"
                >
                  Done
                </button>
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* 3. CURRENTLY ASSIGNED & IN FLIGHT */}
      <div className="space-y-2.5">
        <h3 className="text-xs font-bold text-[#71717a] uppercase tracking-wider flex items-center gap-1.5">
          <UserCheck className="w-3.5 h-3.5 text-[#16a34a]" />
          Currently Assigned & In Progress ({assignedTasks.length})
        </h3>
        <div className="grid gap-2.5">
          {assignedTasks.map((task) => (
            <div
              key={task.id}
              className="p-3.5 rounded-[8px] bg-white border border-[#efefef] flex flex-col md:flex-row md:items-center justify-between gap-3 shadow-[0px_1px_2px_rgba(0,0,0,0.02)]"
            >
              <div>
                <div className="flex items-center gap-2 mb-1">
                  <span className="text-xs font-mono text-[#71717a] font-bold">{task.id}</span>
                  <span className="text-[10px] px-1.5 py-0.2 rounded-[3px] bg-[#f4f4f5] text-[#52525b] font-medium">
                    {task.lane}
                  </span>
                  <span className="text-[11px] font-medium text-[#16a34a]">
                    Assigned to: {task.assignedTo || 'Unspecified'}
                  </span>
                </div>
                <div className="text-xs font-medium text-[#27272a]">{task.task}</div>
              </div>

              <button
                onClick={() => onUpdateStatus(task.id, 'Completed')}
                className="px-3 py-1.5 rounded-[6px] bg-white hover:bg-[#f0fdf4] hover:border-[#bbf7d0] hover:text-[#16a34a] text-[#171717] text-xs font-medium border border-[#e3e3e3] transition-colors flex items-center gap-1.5"
              >
                <CheckCircle className="w-3.5 h-3.5" /> Mark Completed
              </button>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
};
